version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pulsy
    ports:
      - "${PORT}:4321"
    environment:
      - GIN_MODE=${GIN_MODE}
      - PORT=${PORT}
      - TYPE=${TYPE}
      - PROJECT_ID=${PROJECT_ID}
      - PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=${TOKEN_URI}
      - AUTH_PROVIDER_CERT_URL=${AUTH_PROVIDER_CERT_URL}
      - CLIENT_CERT_URL=${CLIENT_CERT_URL}
      - UNIVERSE_DOMAIN=${UNIVERSE_DOMAIN}
      - BUCKET=${BUCKET}
    restart: unless-stopped